### ISSUE TITLE
Fonts too small for figure

### ISSUE THREAD

**Issue by sunworshipper** [calipho-sib/feature-viewer#42]
Currently there is a workaround where you can save the webpage as a pdf and then import it to Illustrator.  However, in general the fonts are too small for a figure and difficult to read.
Some feature where these can be changed would be useful.

A config file would be useful.

**Comment by MatSchaeff** [comment]
Thank you for your suggestion, I will look on how to implement it as an option.
For now, you can use css to enlarge the font-size of some elements. 
For example,
- change the font-size of the sequence : 
```
.seqGroup text{
  font-size:12px
}
```    

- change the font-size of the yaxis : 
```
.yaxis{
  font-size:12px
}
```

**Comment by gabrielctn** [comment]
For anyone interested, I changed more font size like this:
```css
.axis, text.element.domainsText, text.element.pusText, .tick text {
    font-size: 13px!important;
}
```
